solutions = [
  {
    "name"        : "src",
    "url"         : "https://github.com/fire/com-chibifire-fbx-plugin.git",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/godot",
    "url"         : "https://github.com/godotengine/godot",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/cppcodec",
    "url"         : "https://github.com/tplgy/cppcodec",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/godot-cpp/godot_headers",
    "url"         : "https://github.com/GodotNativeTools/godot_headers@b98ac387a1407c16536fdde79466f932433adb0b",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/godot-cpp",
    "url"         : "https://github.com/GodotNativeTools/godot-cpp@342593c78dca5da5d6a29c750bb098301c1612be",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/FBX2glTF",
    "url"         : "https://github.com/facebookincubator/FBX2glTF.git",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/draco",
    "url"         : "https://github.com/google/draco@1.3.0",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/mathfu",
    "url"         : "https://github.com/google/mathfu@v1.1.0",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/mathfu/dependencies/vectorial",
    "url"         : "https://github.com/scoopr/vectorial",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/fifo_map",
    "url"         : "https://github.com/nlohmann/fifo_map",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/json",
    "url"         : "https://github.com/nlohmann/json@v2.1.1",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/stb",
    "url"         : "https://github.com/nothings/stb",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/cxxopts",
    "url"         : "https://github.com/jarro2783/cxxopts@v1.4.4",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
  {
    "name"        : "src/thirdparty/fmt",
    "url"         : "https://github.com/fmtlib/fmt@4.0.0",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {},
  },
]
cache_dir = None

